INSERT INTO public.jobs (
  title,
  description,
  company,
  location,
  company_name,
  location_city,
  location_state,
  slug,
  job_type,
  pay_min,
  pay_max,
  pay_type,
  requirements,
  trades,
  is_featured,
  status,
  company_email,
  company_logo_url,
  how_to_apply
)
VALUES
  (
    'Lead PPF Installer',
    'Run premium installs on exotic and luxury vehicles, train junior installers, and maintain production quality standards.',
    'Apex Film Studio',
    'Scottsdale, AZ',
    'Apex Film Studio',
    'Scottsdale',
    'AZ',
    'lead-ppf-installer-scottsdale-az',
    'full-time',
    35,
    50,
    'hourly',
    '3+ years PPF experience, edge-wrap proficiency, valid driver license.',
    ARRAY['ppf'],
    true,
    'active',
    'hiring@apexfilmstudio.com',
    'https://cdn.tradecareers.com/demo/logos/apex-film-studio-logo.png',
    'Email your portfolio and resume with subject line "Lead PPF Installer".'
  ),
  (
    'Vinyl Wrap Specialist',
    'Install color-change wraps, printed graphics, and fleet branding with clean seams and reliable turnaround.',
    'Metro Wrap Lab',
    'Dallas, TX',
    'Metro Wrap Lab',
    'Dallas',
    'TX',
    'vinyl-wrap-specialist-dallas-tx',
    'full-time',
    28,
    42,
    'hourly',
    '2+ years with cast films, panel planning, and post-heating best practices.',
    ARRAY['vinyl-wrap'],
    false,
    'active',
    'careers@metrowraplab.com',
    'https://cdn.tradecareers.com/demo/logos/metro-wrap-lab-logo.png',
    'Apply through careers@metrowraplab.com with recent install photos.'
  ),
  (
    'Window Tint Technician',
    'Perform automotive tint installs with precision shrinking and final inspection handoff.',
    'Solar Shade Customs',
    'Tampa, FL',
    'Solar Shade Customs',
    'Tampa',
    'FL',
    'window-tint-technician-tampa-fl',
    'full-time',
    24,
    36,
    'hourly',
    'Experience with ceramic films and state compliance standards.',
    ARRAY['window-tint'],
    false,
    'active',
    'jobs@solarshadecustoms.com',
    'https://cdn.tradecareers.com/demo/logos/solar-shade-customs-logo.png',
    'Submit your application and availability by email.'
  ),
  (
    'Ceramic Coating Technician',
    'Prep vehicles, polish paint, and apply ceramic systems for retail and dealership clients.',
    'Gloss District',
    'Charlotte, NC',
    'Gloss District',
    'Charlotte',
    'NC',
    'ceramic-coating-technician-charlotte-nc',
    'full-time',
    52000,
    68000,
    'salary',
    'Paint correction workflow knowledge and high-end finishing experience.',
    ARRAY['ceramic-coating','paint-correction','auto-detailing'],
    false,
    'active',
    'team@glossdistrict.com',
    'https://cdn.tradecareers.com/demo/logos/gloss-district-logo.png',
    'Send resume plus 3 before/after photos.'
  ),
  (
    'Mobile Tint Installer',
    'Handle on-site installs for residential and auto clients around the metro area.',
    'Prime Mobile Tint',
    'Nashville, TN',
    'Prime Mobile Tint',
    'Nashville',
    'TN',
    'mobile-tint-installer-nashville-tn',
    'contract',
    300,
    700,
    'per-job',
    'Own tools, reliable transportation, and excellent customer communication.',
    ARRAY['window-tint'],
    false,
    'active',
    'dispatch@primemobiletint.com',
    'https://cdn.tradecareers.com/demo/logos/prime-mobile-tint-logo.png',
    'Include service area and references in your application email.'
  ),
  (
    'Fleet Wrap Installer',
    'Execute commercial van and box truck wraps for regional business clients.',
    'Northline Graphics',
    'Columbus, OH',
    'Northline Graphics',
    'Columbus',
    'OH',
    'fleet-wrap-installer-columbus-oh',
    'full-time',
    30,
    44,
    'hourly',
    'Comfort with ladders, panel alignment, and rapid production schedules.',
    ARRAY['vinyl-wrap'],
    true,
    'active',
    'production@northlinegraphics.com',
    'https://cdn.tradecareers.com/demo/logos/northline-graphics-logo.png',
    'Apply via email with "Fleet Wrap Installer" in subject.'
  ),
  (
    'Detail and Coating Apprentice',
    'Learn decon wash, paint prep, and coating application in a high-volume boutique shop.',
    'Velocity Detail Co.',
    'Portland, OR',
    'Velocity Detail Co.',
    'Portland',
    'OR',
    'detail-coating-apprentice-portland-or',
    'part-time',
    19,
    24,
    'hourly',
    'Strong work ethic, punctuality, and attention to detail.',
    ARRAY['auto-detailing','ceramic-coating'],
    false,
    'active',
    'hiring@velocitydetail.co',
    'https://cdn.tradecareers.com/demo/logos/velocity-detail-logo.png',
    'Email a short intro and your weekly availability.'
  ),
  (
    'Paint Correction Specialist',
    'Perform multi-step correction and finishing on luxury and performance vehicles.',
    'Refine Auto Lab',
    'Irvine, CA',
    'Refine Auto Lab',
    'Irvine',
    'CA',
    'paint-correction-specialist-irvine-ca',
    'full-time',
    32,
    48,
    'hourly',
    'Rotary and DA polishing experience required.',
    ARRAY['paint-correction','auto-detailing'],
    false,
    'active',
    'careers@refineautolab.com',
    'https://cdn.tradecareers.com/demo/logos/refine-auto-lab-logo.png',
    'Send portfolio and machine setup experience.'
  ),
  (
    'Shop Foreman - Restyling',
    'Oversee daily scheduling, QA checks, and team delivery for wrap, tint, and PPF work.',
    'Torque Customs',
    'Las Vegas, NV',
    'Torque Customs',
    'Las Vegas',
    'NV',
    'shop-foreman-restyling-las-vegas-nv',
    'full-time',
    70000,
    90000,
    'salary',
    '5+ years leadership in aftermarket restyling operations.',
    ARRAY['vinyl-wrap','window-tint','ppf'],
    true,
    'active',
    'ops@torquecustoms.com',
    'https://cdn.tradecareers.com/demo/logos/torque-customs-logo.png',
    'Apply with resume and references.'
  ),
  (
    'Weekend PPF Installer',
    'Support overflow installs on Saturdays and Sundays for high-demand clients.',
    'Shield House',
    'Denver, CO',
    'Shield House',
    'Denver',
    'CO',
    'weekend-ppf-installer-denver-co',
    'part-time',
    32,
    45,
    'hourly',
    'PPF plotting and templating experience preferred.',
    ARRAY['ppf'],
    false,
    'active',
    'jobs@shieldhouse.com',
    'https://cdn.tradecareers.com/demo/logos/shield-house-logo.png',
    'Email current availability and recent work samples.'
  ),
  (
    'Commercial Graphics Installer',
    'Install storefront, wall, and vehicle graphics with a field install crew.',
    'Summit Visual',
    'Minneapolis, MN',
    'Summit Visual',
    'Minneapolis',
    'MN',
    'commercial-graphics-installer-minneapolis-mn',
    'contract',
    26,
    38,
    'hourly',
    'Experience with large format media and site safety protocols.',
    ARRAY['vinyl-wrap'],
    false,
    'draft',
    'recruiting@summitvisual.com',
    'https://cdn.tradecareers.com/demo/logos/summit-visual-logo.png',
    'Send resume and a short installation summary.'
  ),
  (
    'Senior Tint and PPF Technician',
    'Dual-role installer for ceramic tint and front-end PPF packages with upsell support.',
    'Blackline Auto Films',
    'Houston, TX',
    'Blackline Auto Films',
    'Houston',
    'TX',
    'senior-tint-ppf-technician-houston-tx',
    'full-time',
    30,
    46,
    'hourly',
    '3+ years across both tint and PPF, customer handoff skills.',
    ARRAY['window-tint','ppf'],
    true,
    'closed',
    'hiring@blacklineautofilms.com',
    'https://cdn.tradecareers.com/demo/logos/blackline-auto-films-logo.png',
    'This role is currently closed; keep your resume on file by email.'
  )
ON CONFLICT (slug) DO NOTHING;

INSERT INTO public.installers (name, email, location, specialties, bio, portfolio_urls, years_experience, is_available, slug, manage_token)
VALUES
  ('Marcus Hill', 'marcus.hill@wrapworkspro.com', 'Dallas, TX', ARRAY['vinyl-wrap','ppf'], 'Lead wrap installer specializing in matte color-change wraps and full-front PPF packages.', ARRAY['https://instagram.com/marcuswraps','https://drive.google.com/marcusportfolio'], 8, true, 'marcus-hill-dallas-tx', 'seedtoken-marcus-hill'),
  ('Elena Ortiz', 'elena.ortiz@ortiztintlab.com', 'Austin, TX', ARRAY['window-tint','ceramic-coating'], 'Mobile tint and coating specialist focused on premium heat-rejection films.', ARRAY['https://instagram.com/ortiztintlab'], 6, true, 'elena-ortiz-austin-tx', 'seedtoken-elena-ortiz'),
  ('Darnell Brooks', 'darnell.brooks@brooksprotectivefilms.com', 'Phoenix, AZ', ARRAY['ppf','paint-correction'], 'PPF edge-wrap technician with paint correction background on high-end vehicles.', ARRAY['https://www.youtube.com/@brooksppf'], 9, false, 'darnell-brooks-phoenix-az', 'seedtoken-darnell-brooks'),
  ('Kayla Nguyen', 'kayla.nguyen@kaylawrapworks.com', 'San Diego, CA', ARRAY['vinyl-wrap','auto-detailing'], 'Fleet wrap installer and detailer experienced with rapid turnaround commercial jobs.', ARRAY['https://instagram.com/kaylawrapworks'], 5, true, 'kayla-nguyen-san-diego-ca', 'seedtoken-kayla-nguyen'),
  ('Jordan Bell', 'jordan.bell@belltintlabs.com', 'Miami, FL', ARRAY['window-tint'], 'Tint specialist focused on clean shrink patterns and compliance with state film laws.', ARRAY['https://jordanbelltint.com'], 4, true, 'jordan-bell-miami-fl', 'seedtoken-jordan-bell'),
  ('Isaac Romero', 'isaac.romero@romerocoatings.com', 'Las Vegas, NV', ARRAY['ceramic-coating','paint-correction'], 'Correction and coating technician delivering multi-stage polishing and long-term protection.', ARRAY['https://instagram.com/romerocoatings'], 7, true, 'isaac-romero-las-vegas-nv', 'seedtoken-isaac-romero'),
  ('Nia Patel', 'nia.patel@niaprotectivefilms.com', 'Seattle, WA', ARRAY['ppf','window-tint'], 'Certified PPF installer with luxury dealership experience and in-house tint support.', ARRAY['https://instagram.com/niaprotectivefilms'], 10, false, 'nia-patel-seattle-wa', 'seedtoken-nia-patel'),
  ('Cody Ramirez', 'cody.ramirez@milehighdetailco.com', 'Denver, CO', ARRAY['auto-detailing','ceramic-coating'], 'Detail bay lead handling prep, decontamination, and ceramic installs.', ARRAY['https://tiktok.com/@detailcody'], 3, true, 'cody-ramirez-denver-co', 'seedtoken-cody-ramirez'),
  ('Sofia Bennett', 'sofia.bennett@sofiabuilds.com', 'Nashville, TN', ARRAY['vinyl-wrap','window-tint','ppf'], 'Versatile installer across wraps, tint, and PPF with strong customer handoff process.', ARRAY['https://instagram.com/sofiabuilds'], 11, true, 'sofia-bennett-nashville-tn', 'seedtoken-sofia-bennett'),
  ('Trevor King', 'trevor.king@trevorwrapworks.com', 'Charlotte, NC', ARRAY['vinyl-wrap','paint-correction'], 'Color-change wrap specialist known for complex curves and post-wrap refinishing.', ARRAY['https://www.trevorwrapworks.com'], 12, true, 'trevor-king-charlotte-nc', 'seedtoken-trevor-king')
ON CONFLICT (slug) DO NOTHING;

UPDATE public.installers
SET
  instagram = '@marcuswraps',
  tiktok = '@marcuswraps',
  website = 'https://marcuswrapgarage.com',
  youtube = 'https://youtube.com/@marcuswraps',
  phone = '(214) 555-0142'
WHERE slug = 'marcus-hill-dallas-tx';

UPDATE public.installers
SET
  instagram = '@ortiztintlab',
  website = 'https://ortiztintlab.com',
  phone = '(512) 555-0178'
WHERE slug = 'elena-ortiz-austin-tx';

UPDATE public.installers
SET
  tiktok = '@detailcody',
  website = 'https://detailcody.com',
  youtube = 'https://youtube.com/@detailcody'
WHERE slug = 'cody-ramirez-denver-co';
